
#Data Cleaning dan Feature Engineering untuk Teknik Industri

Sesi ini membahas tahapan preprocessing data yang merupakan fondasi sebelum pembangunan model machine learning. Dalam praktik data science, kualitas model sangat dipengaruhi oleh kualitas data masukan. Oleh karena itu, penanganan missing value, identifikasi inkonsistensi data, transformasi variabel kategorikal, standardisasi variabel numerik, serta pembentukan fitur turunan merupakan kompetensi yang esensial.


## 1. Mengapa Preprocessing Penting?

Preprocessing merupakan tahapan untuk menyiapkan data agar layak digunakan pada proses analisis lanjutan dan pemodelan machine learning. Permasalahan umum pada data industri meliputi nilai hilang, format yang tidak konsisten, data kategorikal yang belum dapat dibaca model, skala numerik yang berbeda jauh, dan variabel yang belum cukup representatif.

Dalam konteks teknik industri, preprocessing penting karena data operasional sering berasal dari berbagai sumber, seperti mesin, operator, inspeksi kualitas, dan sistem produksi. Oleh sebab itu, sebelum melakukan prediksi, data perlu dibersihkan dan ditransformasikan secara sistematis.

## 3. Deskripsi Dataset Studi Kasus

Dataset menggambarkan data produksi per shift dengan sejumlah variabel operasional, kualitas, dan status keterlambatan. Dalam dataset ini sengaja disisipkan beberapa missing value agar mahasiswa dapat berlatih melakukan pembersihan data secara nyata.

Variabel `Status_Keterlambatan` juga disertakan sebagai contoh target kategorikal untuk persiapan sesi pemodelan klasifikasi pada pertemuan berikutnya.

In [ ]:
# =============================================================================
# IMPORT LIBRARY YANG DIPERLUKAN
# =============================================================================
# pandas: manipulasi data tabular
# numpy: operasi numerik
# sklearn.preprocessing: encoding dan scaling

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

print('Library untuk preprocessing siap digunakan')

Library untuk preprocessing siap digunakan

In [ ]:
# =============================================================================
# MEMBUAT DATSET
# =============================================================================

import pandas as pd

data = [
    {
        'Tanggal': '2026-01-05',
        'Shift': 'Pagi',
        'Mesin': 'M1',
        'Output_Unit': 120,
        'Downtime_Menit': 30,
        'Defect_Unit': 5,
        'Operator_Hadir': 8,
        'Suhu_Mesin': 72,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Tidak'
    },
    {
        'Tanggal': '2026-01-05',
        'Shift': 'Siang',
        'Mesin': 'M1',
        'Output_Unit': 118,
        'Downtime_Menit': 35,
        'Defect_Unit': 6,
        'Operator_Hadir': 8,
        'Suhu_Mesin': 74,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Tidak'
    },
    {
        'Tanggal': '2026-01-06',
        'Shift': 'Pagi',
        'Mesin': 'M1',
        'Output_Unit': 135,
        'Downtime_Menit': 25,
        'Defect_Unit': 4,
        'Operator_Hadir': 8,
        'Suhu_Mesin': 70,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Tidak'
    },
    {
        'Tanggal': '2026-01-06',
        'Shift': 'Siang',
        'Mesin': 'M1',
        'Output_Unit': 132,
        'Downtime_Menit': 28,
        'Defect_Unit': 5,
        'Operator_Hadir': 8,
        'Suhu_Mesin': 71,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Tidak'
    },
    {
        'Tanggal': '2026-01-07',
        'Shift': 'Pagi',
        'Mesin': 'M2',
        'Output_Unit': 128,
        'Downtime_Menit': 40,
        'Defect_Unit': 6,
        'Operator_Hadir': 7,
        'Suhu_Mesin': 79,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Ya'
    },
    {
        'Tanggal': '2026-01-07',
        'Shift': 'Siang',
        'Mesin': 'M2',
        'Output_Unit': 125,
        'Downtime_Menit': 42,
        'Defect_Unit': 7,
        'Operator_Hadir': 7,
        'Suhu_Mesin': 81,
        'Target_Unit': 130,
        'Status_Keterlambatan': 'Ya'
    },
    {
        'Tanggal': '2026-01-08',
        'Shift': 'Pagi',
        'Mesin': 'M2',
        'Output_Unit': 140,
        'Downtime_Menit': 20,
        'Defect_Unit': 3,
        'Operator_Hadir': 8,
        'Suhu_Mesin': 69,
        'Target_Unit': 135,
        'Status_Keterlambatan': 'Tidak'
    }
]

df = pd.DataFrame(data)
df.head()

,Tanggal,Shift,Mesin,Output_Unit,Downtime_Menit,Defect_Unit,Operator_Hadir,Suhu_Mesin,Target_Unit,Status_Keterlambatan
0,2026-01-05,Pagi,M1,120,30,5,8,72,130,Tidak
1,2026-01-05,Siang,M1,118,35,6,8,74,130,Tidak
2,2026-01-06,Pagi,M1,135,25,4,8,70,130,Tidak
3,2026-01-06,Siang,M1,132,28,5,8,71,130,Tidak
4,2026-01-07,Pagi,M2,128,40,6,7,79,130,Ya


## 4. Inspeksi Awal Data

Tahap pertama adalah memeriksa struktur data, tipe variabel, dan kemungkinan adanya missing value. Langkah ini penting agar setiap proses cleaning dilakukan berdasarkan kondisi data yang sebenarnya, bukan asumsi.

In [ ]:
# Menampilkan lima baris pertama untuk memahami struktur tabel
df.head()

,Tanggal,Shift,Mesin,Output_Unit,Downtime_Menit,Defect_Unit,Operator_Hadir,Suhu_Mesin,Target_Unit,Status_Keterlambatan
0,2026-01-05,Pagi,M1,120,30,5,8,72,130,Tidak
1,2026-01-05,Siang,M1,118,35,6,8,74,130,Tidak
2,2026-01-06,Pagi,M1,135,25,4,8,70,130,Tidak
3,2026-01-06,Siang,M1,132,28,5,8,71,130,Tidak
4,2026-01-07,Pagi,M2,128,40,6,7,79,130,Ya

In [ ]:
# Menampilkan informasi kolom, jumlah non-null, dan tipe data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Tanggal               7 non-null      object
 1   Shift                 7 non-null      object
 2   Mesin                 7 non-null      object
 3   Output_Unit           7 non-null      int64
 4   Downtime_Menit        7 non-null      int64
 5   Defect_Unit           7 non-null      int64
 6   Operator_Hadir        7 non-null      int64
 7   Suhu_Mesin            7 non-null      int64
 8   Target_Unit           7 non-null      int64
 9   Status_Keterlambatan  7 non-null      object
dtypes: int64(6), object(4)
memory usage: 692.0+ bytes

In [ ]:
# Menampilkan statistik deskriptif untuk variabel numerik
df.describe()

,Output_Unit,Downtime_Menit,Defect_Unit,Operator_Hadir,Suhu_Mesin,Target_Unit
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,128.285714,31.428571,5.142857,7.714286,73.714286,130.714286
std,7.973169,7.997023,1.345185,0.487950,4.608481,1.889822
min,118.000000,20.000000,3.000000,7.000000,69.000000,130.000000
25%,122.500000,26.500000,4.500000,7.500000,70.500000,130.000000
50%,128.000000,30.000000,5.000000,8.000000,72.000000,130.000000
75%,133.500000,37.500000,6.000000,8.000000,76.500000,130.000000
max,140.000000,42.000000,7.000000,8.000000,81.000000,135.000000

In [ ]:
# Menghitung jumlah missing value per kolom
df.isnull().sum()

Tanggal                 0
Shift                   0
Mesin                   0
Output_Unit             0
Downtime_Menit          0
Defect_Unit             0
Operator_Hadir          0
Suhu_Mesin              0
Target_Unit             0
Status_Keterlambatan    0
dtype: int64

## 5. Penanganan Missing Value

Missing value dapat ditangani dengan beberapa pendekatan, seperti menghapus baris, menghapus kolom, atau melakukan imputasi. Pada sesi ini digunakan imputasi sederhana agar mahasiswa memahami prinsip dasar tanpa kompleksitas yang berlebihan.

- Variabel numerik diisi dengan nilai rata-rata.
- Variabel kategorikal dapat diisi dengan modus jika diperlukan.

In [ ]:
# =============================================================================
# MENANGANI MISSING VALUE PADA KOLOM NUMERIK
# =============================================================================
# fillna() digunakan untuk mengganti nilai kosong.
# Di sini, nilai kosong pada Downtime_Menit dan Defect_Unit
# diganti dengan rata-rata kolom masing-masing.

df['Downtime_Menit'] = df['Downtime_Menit'].fillna(df['Downtime_Menit'].mean())
df['Defect_Unit'] = df['Defect_Unit'].fillna(df['Defect_Unit'].mean())

# Memeriksa ulang missing value
df.isnull().sum()

Tanggal                 0
Shift                   0
Mesin                   0
Output_Unit             0
Downtime_Menit          0
Defect_Unit             0
Operator_Hadir          0
Suhu_Mesin              0
Target_Unit             0
Status_Keterlambatan    0
dtype: int64

## 6. Pemeriksaan Duplikasi dan Konsistensi

Pada tahap ini, mahasiswa perlu memahami bahwa data duplikat dapat mengganggu interpretasi hasil. Pemeriksaan duplikasi merupakan prosedur standar dalam preprocessing data.

In [ ]:
# Mengecek jumlah baris yang terduplikasi
df.duplicated().sum()

np.int64(0)

## 7. Feature Engineering: Membentuk Variabel Turunan

Feature engineering adalah proses membangun variabel baru dari data yang sudah ada agar lebih representatif terhadap fenomena yang dianalisis. Dalam konteks teknik industri, variabel turunan sering kali lebih informatif dibandingkan variabel mentah.

Pada sesi ini akan dibuat:
- `Selisih_Target` = Output aktual - Target
- `Defect_Rate` = Defect / Output
- `Produktivitas_Operator` = Output / Operator hadir

In [ ]:
# =============================================================================
# MEMBENTUK FITUR TURUNAN
# =============================================================================
# Kolom baru dibuat dengan operasi matematika sederhana antarvariabel.

df['Selisih_Target'] = df['Output_Unit'] - df['Target_Unit']
df['Defect_Rate'] = df['Defect_Unit'] / df['Output_Unit']
df['Produktivitas_Operator'] = df['Output_Unit'] / df['Operator_Hadir']

# Menampilkan hasil fitur baru
df.head()

,Tanggal,Shift,Mesin,Output_Unit,Downtime_Menit,Defect_Unit,Operator_Hadir,Suhu_Mesin,Target_Unit,Status_Keterlambatan,Selisih_Target,Defect_Rate,Produktivitas_Operator
0,2026-01-05,Pagi,M1,120,30,5,8,72,130,Tidak,-10,0.041667,15.000000
1,2026-01-05,Siang,M1,118,35,6,8,74,130,Tidak,-12,0.050847,14.750000
2,2026-01-06,Pagi,M1,135,25,4,8,70,130,Tidak,5,0.029630,16.875000
3,2026-01-06,Siang,M1,132,28,5,8,71,130,Tidak,2,0.037879,16.500000
4,2026-01-07,Pagi,M2,128,40,6,7,79,130,Ya,-2,0.046875,18.285714

## 8. Encoding Variabel Kategorikal

Sebagian besar algoritma machine learning membutuhkan input numerik. Oleh karena itu, variabel kategorikal seperti `Shift`, `Mesin`, dan `Status_Keterlambatan` perlu diubah menjadi bentuk numerik.

Pada sesi ini digunakan `LabelEncoder` untuk pengenalan awal. Pada tahap lebih lanjut, mahasiswa dapat diperkenalkan pada one-hot encoding.

In [ ]:
# =============================================================================
# ENCODING DATA KATEGORIKAL
# =============================================================================
# LabelEncoder mengubah kategori teks menjadi angka.
# Contoh: Pagi -> 0, Siang -> 1 (tergantung hasil encoder)

le_shift = LabelEncoder()
le_mesin = LabelEncoder()
le_status = LabelEncoder()

df['Shift_Encoded'] = le_shift.fit_transform(df['Shift'])
df['Mesin_Encoded'] = le_mesin.fit_transform(df['Mesin'])
df['Status_Encoded'] = le_status.fit_transform(df['Status_Keterlambatan'])

df[['Shift','Shift_Encoded','Mesin','Mesin_Encoded','Status_Keterlambatan','Status_Encoded']].head()

,Shift,Shift_Encoded,Mesin,Mesin_Encoded,Status_Keterlambatan,Status_Encoded
0,Pagi,0,M1,0,Tidak,0
1,Siang,1,M1,0,Tidak,0
2,Pagi,0,M1,0,Tidak,0
3,Siang,1,M1,0,Tidak,0
4,Pagi,0,M2,1,Ya,1

## 9. Scaling Variabel Numerik

Feature scaling diperlukan ketika variabel numerik memiliki skala yang sangat berbeda. Misalnya, `Downtime_Menit` dan `Output_Unit` memiliki rentang nilai yang berbeda. Beberapa algoritma machine learning, khususnya yang berbasis jarak, sangat sensitif terhadap perbedaan skala.

Pada sesi ini digunakan `StandardScaler`, yang mengubah data sehingga memiliki rata-rata mendekati nol dan simpangan baku mendekati satu.

In [ ]:
# =============================================================================
# STANDARDISASI FITUR NUMERIK
# =============================================================================
# StandardScaler mengubah data numerik menjadi skala standar.
# Kolom yang dipilih adalah variabel numerik utama dan fitur turunan.

scaler = StandardScaler()

numeric_cols = ['Output_Unit', 'Downtime_Menit', 'Defect_Unit', 'Suhu_Mesin',
                'Selisih_Target', 'Defect_Rate', 'Produktivitas_Operator']

scaled_data = scaler.fit_transform(df[numeric_cols])

# Membuat DataFrame baru agar hasil lebih mudah dibaca
df_scaled = pd.DataFrame(scaled_data, columns=[col + '_Scaled' for col in numeric_cols])

df_scaled.head()

,Output_Unit_Scaled,Downtime_Menit_Scaled,Defect_Unit_Scaled,Suhu_Mesin_Scaled,Selisih_Target_Scaled,Defect_Rate_Scaled,Produktivitas_Operator_Scaled
0,-1.122464,-0.192951,-0.114708,-0.401790,-1.185116,0.093635,-1.325846
1,-1.393403,0.482377,0.688247,0.066965,-1.498166,0.913395,-1.523012
2,0.909583,-0.868279,-0.917663,-0.870544,1.162755,-0.981162,0.152905
3,0.503173,-0.463082,-0.114708,-0.636167,0.693181,-0.244588,-0.142845
4,-0.038706,1.157706,0.688247,1.238852,0.067082,0.558691,1.265489

## 10. Menyusun Dataset Siap Model

Setelah cleaning, feature engineering, encoding, dan scaling selesai, langkah berikutnya adalah menyusun dataset yang siap digunakan untuk machine learning.

In [ ]:
# Menggabungkan beberapa kolom hasil preprocessing ke dalam satu tabel akhir
df_final = pd.concat([
    df[['Shift_Encoded', 'Mesin_Encoded', 'Status_Encoded']],
    df_scaled
], axis=1)

df_final.head()

,Shift_Encoded,Mesin_Encoded,Status_Encoded,Output_Unit_Scaled,Downtime_Menit_Scaled,Defect_Unit_Scaled,Suhu_Mesin_Scaled,Selisih_Target_Scaled,Defect_Rate_Scaled,Produktivitas_Operator_Scaled
0,0,0,0,-1.122464,-0.192951,-0.114708,-0.401790,-1.185116,0.093635,-1.325846
1,1,0,0,-1.393403,0.482377,0.688247,0.066965,-1.498166,0.913395,-1.523012
2,0,0,0,0.909583,-0.868279,-0.917663,-0.870544,1.162755,-0.981162,0.152905
3,1,0,0,0.503173,-0.463082,-0.114708,-0.636167,0.693181,-0.244588,-0.142845
4,0,1,1,-0.038706,1.157706,0.688247,1.238852,0.067082,0.558691,1.265489

## 11. Kesimpulan

Dari tahapan yang telah dilakukan, kita telah mempelajari prinsip penting:
- Missing value harus ditangani agar model tidak gagal atau menghasilkan bias.
- Variabel kategorikal perlu diubah menjadi numerik agar dapat diproses algoritma.
- Fitur turunan membantu memperjelas representasi fenomena industri.
- Scaling dibutuhkan agar variabel dengan rentang besar tidak mendominasi perhitungan model tertentu.

Dengan demikian, preprocessing bukan sekadar tahap teknis, melainkan bagian dari konstruksi kualitas data untuk mendukung validitas analisis.